Moved more functionality to *Pattern classes.
sjoerdjob/django pull request #2
Opened 2017-08-17 19:53 UTC by knbk

I've made some additional changes based on your comments on my previous PR. I was actually aiming to get all translation-related code into the `*Pattern` classes, but as it turns out that is difficult to do without affecting the performance of `reverse()` too much.

2017-08-18 17:15 UTC, sjoerdjob requested changes
Suggestion: adding `pattern_name` to the `*Pattern` (or `CheckURLMixin`) base class, and the fallout cleanup.

Also: reconsider if we would allow the possibility of locale-dependent converters.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +    def describe(self, pattern_name):
From what I can see, given a specific `*Pattern`, it's *always* called with the same `pattern_name`. As such, it seems to me that the `*Pattern` should be the owner of the `pattern_name` (maybe alongside `URLResolver`/`URLResolver`, maybe instead of).

Some side-remarks about `describe`/`pattern_name`:

* It's only supplied to/for `URLPattern` (and not the `URLResolver`), so only if `is_endpoint=True`.
* The formatting as used in `.describe()` is *almost* the same as used in `technical_404` (the almost being whitespace differences).

Hence: if we make `RoutePattern`/`RegexPattern` owner of `.name`, we can replace `.describe(self)` with `.__str__(self)`, and remove the special casing in `technical_404`.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +    def check(self, pattern_name):
Given suggestion above, we should be able to get rid of `pattern_name` as argument here.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +    def _check_include_trailing_dollar(self, pattern_name):
Given suggestion above, we should be able to get rid of `pattern_name` as argument here.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +    def _check_pattern_startswith_slash(self, pattern_name):
Given suggestion above, we should be able to get rid of `pattern_name` as argument here.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +        self.converters = _route_to_regex(str(route), is_endpoint)[1]
*big* assumption here: the `converters` are the same for any translation.

Theoretically, it could be that the converters are different...

```
Dutch: /<decimal_with_comma:amount>/
English: /<decimal_with_period:amount>/
```

(Yes, highly theoretical, but seeing as the converters are part of the translatable string, we should either support choosing having them different, or check for it, not sure).

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +        return '<%s %s %s>' % (self.__class__.__name__, self.name, self.pattern)
Assuming we can change `repr`: `'<%s %s>'.format(self.__class__.__name__, self.pattern.describe(self.name))` would also make sense, and that would become `'<%s %s>'.format(self.__class__.__name__, self.pattern)` under the suggested changes above.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
>              kwargs.update(self.default_args)
To be honest, I'm not a fan of `default_args` overriding the parsed `kwargs` (and always suspect it's a bug), but let's leave it put because that's how it currently works.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +            new_path = match[0]
Would the following be better?

```
sub_path, match_args, match_kwargs = match
```

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> +                        sub_match_dict = dict(match[2], **self.default_kwargs)
Here a minor difference occurs: in the old version, the `default_kwargs` were also run through the converter, in the new version, they're not. I think I prefer the new version, but just mentioning the change.

2017-08-18 17:15 UTC, sjoerdjob commented on django/contrib/admindocs/views.py
> +                base + p.pattern.regex.pattern,
It's a bit sad that for the new-style patterns, in the admindocs it's processed as "simplified => regex => simplify_regex" losing the (maybe useful?) type information.

(Please don't fix it, it can wait until the base PR is merged, I think).

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
>          # Short-circuit if called recursively in this thread to prevent
Seriously wondering why one would even want to support cyclicly nested patterns... From what I can see, the cyclic nature complicates `_populate` (albeit just a bit), but also prevents improvements to the logic of `reverse`. And only using `args` (not kwargs) it brings a possible benefit.

2017-08-18 17:15 UTC, sjoerdjob commented on django/urls/resolvers.py
> -        # because there might be cyclic dependencies.
Is the problem with cyclic dependencies solved? I *think* so because it has been moved to `pattern` instead.

2017-08-22 22:16 UTC, knbk commented on django/urls/resolvers.py
> +        self.converters = _route_to_regex(str(route), is_endpoint)[1]
I think that rather than localising the route to use different converters, the converters themselves should be localised where necessary. The `regex` attribute on the various converters can be a `LocaleRegexDescriptor` if localisation is needed. If we allow people to use different converters per language, I can only see it end up in a big mess.

If this proves to be a problem, we can add a systems check that iterates `settings.LANGUAGES`. For now I don't think that's necessary.

2017-08-22 22:16 UTC, knbk commented on django/urls/resolvers.py
> +    def describe(self, pattern_name):
I think semantically, the name belongs to `URLPattern`, but I agree that passing it to the `*Pattern` classes makes for cleaner code. There are quite a lot of places that use `pattern.name`, so I don't think we should remove it from `URLPattern` entirely. 

There's also a different use of quotes around the route, and there are some places that need the route and name separately. I think we need to keep the separation -- quotes around the route in running sentences, no quotes in technical messages with multiple patterns concatenated, and no name when the name is needed separately.

2017-08-22 22:16 UTC, knbk commented on django/urls/resolvers.py
> -        # because there might be cyclic dependencies.
Yes, it's been solved. The populated attributes on child resolvers are only accessed on non-namespaced includes, while cyclic dependencies are only possible across namespaces.

2017-08-22 22:16 UTC, knbk commented on django/urls/resolvers.py
>          # Short-circuit if called recursively in this thread to prevent
I honestly don't think there are any reasonable use-cases, but in my attempts to remove this I encountered cyclic dependencies in Django's own test suite, which raises the barrier to just remove it entirely.

2017-08-22 22:16 UTC, knbk commented on django/urls/resolvers.py
> +                        sub_match_dict = dict(match[2], **self.default_kwargs)
Didn't realise this, but I think it makes sense.

2017-08-22 22:16 UTC, knbk commented on django/contrib/admindocs/views.py
> +                base + p.pattern.regex.pattern,
We can use `base + str(p.pattern)`, so it's an easy fix.

2017-08-23 04:19 UTC, sjoerdjob approved these changes
Thank you for incorporating the changes. Looks good to me.

2017-08-23 04:20 UTC, merged